// Code generated by Kitex v0.4.4. DO NOT EDIT.

package favorite

import (
	"context"
	api "github.com/Liujony/tiktokapi/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceInfo
}

var favoriteServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Favorite"
	handlerType := (*api.Favorite)(nil)
	methods := map[string]kitex.MethodInfo{
		"Action": kitex.NewMethodInfo(actionHandler, newFavoriteActionArgs, newFavoriteActionResult, false),
		"List":   kitex.NewMethodInfo(listHandler, newFavoriteListArgs, newFavoriteListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.FavoriteActionArgs)
	realResult := result.(*api.FavoriteActionResult)
	success, err := handler.(api.Favorite).Action(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteActionArgs() interface{} {
	return api.NewFavoriteActionArgs()
}

func newFavoriteActionResult() interface{} {
	return api.NewFavoriteActionResult()
}

func listHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.FavoriteListArgs)
	realResult := result.(*api.FavoriteListResult)
	success, err := handler.(api.Favorite).List(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteListArgs() interface{} {
	return api.NewFavoriteListArgs()
}

func newFavoriteListResult() interface{} {
	return api.NewFavoriteListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Action(ctx context.Context, req *api.DouyinFavoriteActionRequest) (r *api.DouyinFavoriteActionResponse, err error) {
	var _args api.FavoriteActionArgs
	_args.Req = req
	var _result api.FavoriteActionResult
	if err = p.c.Call(ctx, "Action", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) List(ctx context.Context, req *api.DouyinFavoriteListRequest) (r *api.DouyinFavoriteListResponse, err error) {
	var _args api.FavoriteListArgs
	_args.Req = req
	var _result api.FavoriteListResult
	if err = p.c.Call(ctx, "List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
